#NUMPY.

In [1]:
import numpy as np

In [60]:
a= [1,2,3,4]
b= (1,2,3,4) 

In [61]:
#Convert List to array
c= np.array(a)
print(c)
print(type(c))

[1 2 3 4]
<class 'numpy.ndarray'>


In [62]:
#Convert Tuple to array
d= np.array(b)
print(d)
print(type(d))

[1 2 3 4]
<class 'numpy.ndarray'>


In [63]:
c

array([1, 2, 3, 4])

In [64]:
#shape - tell shape of array

print(c.shape)
print(d.shape)

(4,)
(4,)


In [65]:
# ndim - tells dimension of array
print(c.ndim)
print(d.ndim)

1
1


In [66]:
# reshape (1d - 2d) - to change the shape of array
e= c.reshape(2,2)
print(e)
print(e.ndim)

[[1 2]
 [3 4]]
2


In [67]:
s= {1,2,3,4}

In [68]:
q= np.array(s)

In [69]:
# set 4 element but shape is blank
print(q.shape)

()


In [70]:
# set 4 elements but dimension is 0
q.ndim

0

In [71]:
# cannot reshape set convert to array
q.reshape(2,2)

ValueError: cannot reshape array of size 1 into shape (2,2)

ARRAY treats entire set as single element(cause set is unordered)                                    
Single element array is called scalar array


In [ ]:
#2D ARRAY
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#3D ARRAY
np.array([[[1,2,3],[4,5,6]]])

array([[[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
c.dtype

dtype('int64')

In [ ]:
# dtype - can use to change data type
a = np.array([1,2,3,4], dtype= "float")

In [ ]:
print(a)
a.dtype

[1. 2. 3. 4.]


dtype('float64')

In [ ]:
# dtype object stores any type of data whether it is numeric non numeric
a = np.array([1,2,3,4], dtype= "object")
print(a)
a.dtype

[1 2 3 4]


dtype('O')

In [ ]:
# form array using inbuilt function

In [ ]:
# arange 
print(np.arange(10))
print(np.arange(4,10))
print(np.arange(2,10,2))
print(np.arange(10, dtype = "float"))
a= np.arange(10, dtype = "int64")



[0 1 2 3 4 5 6 7 8 9]
[4 5 6 7 8 9]
[2 4 6 8]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
# reshape (3,4) or (4,2)-error,only (2,5) or (5,2) - works
a.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
np.arange(20).reshape(2,5,2)



array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [ ]:
# np.ones- create a matrix where every element is 1.
print(np.ones(5))
print()
print(np.ones((3,3)))
print()
print(np.ones((3,3), dtype ="object"))

[1. 1. 1. 1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
# np.zeros- create a matrix where every element is 0
print(np.zeros(5))
print()
print(np.zeros((4,4)))
print()
print(np.zeros((4,4), dtype= "int32"))

[0. 0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
# np.full- creates an array out of desired number
print(np.full(5,12))
print()
print(np.full((5,5),24))
print()
print(np.full((4,4), 68, dtype= "float"))

[12 12 12 12 12]

[[24 24 24 24 24]
 [24 24 24 24 24]
 [24 24 24 24 24]
 [24 24 24 24 24]
 [24 24 24 24 24]]

[[68. 68. 68. 68.]
 [68. 68. 68. 68.]
 [68. 68. 68. 68.]
 [68. 68. 68. 68.]]


In [ ]:
# Identity matrix.
print(np.identity(5))
print()
print(np.identity(5, dtype= "object"))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [ ]:
# random matrix of decimal number
np.random.random((4,4)) #every element will be between 0-1

array([[0.74619761, 0.84537766, 0.28262621, 0.30704388],
       [0.11226468, 0.75210597, 0.88675031, 0.43898695],
       [0.23265092, 0.97758827, 0.57310286, 0.08407174],
       [0.89651202, 0.3137113 , 0.77697465, 0.45811402]])

In [ ]:
# non decimal matrix
print(np.random.randint(10))
print()
print(np.random.randint(30,51))
print()
print(np.random.randint(1,20, size=(3,3)))
print()
print(np.random.randint(1,100, size=(4,5,6))) 

8

48

[[ 3  8  4]
 [ 8 11  2]
 [ 7 10 10]]

[[[36 91 97 28 97 68]
  [55 86 49 90 32 92]
  [ 8 92 30 48  8 46]
  [ 4 14 41  1  8 98]
  [39 83  1 66 34 35]]

 [[62 64 91  8 59 11]
  [32 95 24 28 29 40]
  [ 1  4 66 70 82  3]
  [65 88  3 40 29 35]
  [91 93 88 93  3 40]]

 [[89 83 35 34 30 50]
  [55 73 72 56 15  5]
  [56 73 75 25 81 92]
  [88 53 34 23 63 24]
  [97 99 73 82 72 98]]

 [[45 92 36 52 13 56]
  [23 59 22 45  1 53]
  [11 56 97 25 14 37]
  [91 32 52 64 18 42]
  [16 76 74 39 17 45]]]


In [ ]:
import time

In [ ]:
a=time.time()

In [ ]:
b=time.time()

In [ ]:
b-a

16.212430238723755

In [ ]:
# Execution time [ speed ]
#LIST
a = [i for i in range(10000000)]   
# a=[]
# for i in range(10000000);
# a.append(i)
b= [i for i in range(10000000,20000000)]
c=[]
start= time.time()
for i in range(len(a)):
    c.append(a[i]+b[i])
end= time.time()
print(f"Total duration{end-start}")

Total duration2.0528228282928467


In [ ]:
# ARRAY
a= np.arange(10000000)
b= np.arange(10000000,20000000)

start= time.time()
c= a+b
end= time.time()
print(f"Total duration{end-start}")


Total duration0.19597625732421875


ABOVE SHOWS, ARRAY IS MUCH FASTER THAN LIST 

In [ ]:
# MEMORY
import sys

In [ ]:
#LIST
a = [i for i in range(10000000)]  
sys.getsizeof(a)


89095160

In [ ]:
#ARRAY
a = np.arange(1000000, dtype=np.int32)

print(a.dtype)
print(sys.getsizeof(a))

int32
4000112


MEMORY TAKEN BY LIST IS APPROX DOUBLE THE MEMORY TAKEN BY ARRAY,                                        
HENCE ARRAY IS BOTH MEMORY AND SPEED EFFICIENT THAN LIST

In [ ]:
a= np.random.randint(1,10, size=(3,3))
a

array([[1, 6, 9],
       [3, 2, 8],
       [3, 4, 3]], dtype=int32)

In [ ]:
a.size # tells total no. of elements in an array/matrix

9

In [ ]:
a.itemsize # tells how much space an single element is occupying in memory

4

In [ ]:
b=a.astype(object) #changes datatype 

In [ ]:
b.size

9

In [ ]:
b.itemsize

8

In [ ]:
c= np.array([[3,"abc"],["q","we"]])
c

array([['3', 'abc'],
       ['q', 'we']], dtype='<U21')

In [ ]:
c= np.array([[3,"abc"],["q","we"]])
c.itemsize

84

In [ ]:
a= np.array([["a", 3333333333333333333333333],["b","c"]])
a

array([['a', 3333333333333333333333333],
       ['b', 'c']], dtype=object)

ABOVE 19 CHARACTERS, PYTHON NOI USES U21 OR U19 BASICALLY NOT CONSIDER IT A INT, INSTEAD USES OBJECT

In [ ]:
 # python -- slow processing - object.

## INDEXING AND SLICING

In [ ]:
a= np.random.randint(10,40, size= (5,7),)

In [ ]:
a

array([[21, 13, 27, 22, 23, 17, 31],
       [38, 12, 23, 17, 27, 17, 30],
       [12, 17, 19, 21, 10, 33, 16],
       [27, 22, 34, 33, 39, 30, 18],
       [32, 37, 37, 39, 32, 15, 36]], dtype=int32)

In [ ]:
a[2,2]  #single value access

np.int32(19)

In [ ]:
a[0] #access particular row.

array([21, 13, 27, 22, 23, 17, 31], dtype=int32)

In [ ]:
a[1:4] #acess from _ row to _ row #bunch of rows

array([[38, 12, 23, 17, 27, 17, 30],
       [12, 17, 19, 21, 10, 33, 16],
       [27, 22, 34, 33, 39, 30, 18]], dtype=int32)

In [ ]:
a[1:4,0] # rows and columns 

array([38, 12, 27], dtype=int32)

In [ ]:
a[1:4, 1:4] # bunch of rows and columns

array([[12, 23, 17],
       [17, 19, 21],
       [22, 34, 33]], dtype=int32)

In [ ]:
a[:,0:3]

array([[21, 13, 27],
       [38, 12, 23],
       [12, 17, 19],
       [27, 22, 34],
       [32, 37, 37]], dtype=int32)

In [ ]:
a[:,:]

array([[21, 13, 27, 22, 23, 17, 31],
       [38, 12, 23, 17, 27, 17, 30],
       [12, 17, 19, 21, 10, 33, 16],
       [27, 22, 34, 33, 39, 30, 18],
       [32, 37, 37, 39, 32, 15, 36]], dtype=int32)

In [ ]:
a[:,[1,3,5]] # all rows and particular columns

array([[13, 22, 17],
       [12, 17, 17],
       [17, 21, 33],
       [22, 33, 30],
       [37, 39, 15]], dtype=int32)

In [ ]:
# boolean indexing

In [ ]:
a>30

array([[False, False, False, False, False, False,  True],
       [ True, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False],
       [False, False,  True,  True,  True, False, False],
       [ True,  True,  True,  True,  True, False,  True]])

In [ ]:
a[a>30]

array([31, 38, 33, 34, 33, 39, 32, 37, 37, 39, 32, 36], dtype=int32)

In [ ]:
a[~(a>30)]

array([21, 13, 27, 22, 23, 17, 12, 23, 17, 27, 17, 30, 12, 17, 19, 21, 10,
       16, 27, 22, 30, 18, 15], dtype=int32)

In [ ]:
a= np.random.randint(1,20, size=(4,4,4))

In [ ]:
a


array([[[ 1,  1,  6, 18],
        [15, 11, 15,  2],
        [15,  8,  7,  5],
        [ 1,  2,  2, 14]],

       [[18,  7,  3, 17],
        [ 5, 15,  3, 12],
        [ 8,  2, 11, 14],
        [16, 10,  8,  2]],

       [[ 6, 12, 16, 19],
        [19,  6, 18,  8],
        [18,  9,  6, 18],
        [19, 15, 11,  9]],

       [[17, 16,  2,  8],
        [ 3, 13, 15,  8],
        [ 7, 11, 19, 15],
        [18, 14, 16,  3]]], dtype=int32)

In [ ]:
a[0:2, 1:3, 1:3]

array([[[11, 15],
        [ 8,  7]],

       [[15,  3],
        [ 2, 11]]], dtype=int32)

## OPERATIONS ON ARRAYS.

In [ ]:
a= np.random.randint(1,15, size=(3,3))
b= np.random.randint(1,15, size=(3,3))

In [ ]:
a


array([[ 2,  2,  9],
       [ 5,  7, 10],
       [13,  4,  9]], dtype=int32)

In [ ]:
b

array([[ 3, 14, 11],
       [ 3,  6, 14],
       [ 1,  9, 12]], dtype=int32)

In [ ]:
#OPERATION OF ARRAY WITH SCALER VALUES.

In [ ]:
a*5 # similar for /

array([[10, 10, 45],
       [25, 35, 50],
       [65, 20, 45]], dtype=int32)

In [ ]:
a+5  # similar for -

array([[ 7,  7, 14],
       [10, 12, 15],
       [18,  9, 14]], dtype=int32)

In [ ]:
# OPERATIONS OF ARRAY WITH ARRAY

In [ ]:
a+b

array([[ 5, 16, 20],
       [ 8, 13, 24],
       [14, 13, 21]], dtype=int32)

In [ ]:
a*b # relative element gets multiplied, NOT MATRIX MULTIPLICATION

    

array([[  6,  28,  99],
       [ 15,  42, 140],
       [ 13,  36, 108]], dtype=int32)

In [ ]:
a/b # relative element gets divide, NOT DIVISION OF MATRIX

array([[ 0.66666667,  0.14285714,  0.81818182],
       [ 1.66666667,  1.16666667,  0.71428571],
       [13.        ,  0.44444444,  0.75      ]])

In [ ]:
a.dot(b) # MATRIX MULTIPLICATION

array([[ 21, 121, 158],
       [ 46, 202, 273],
       [ 60, 287, 307]], dtype=int32)

In [ ]:
np.dot(a,b) # a.dot(b) and this both are same

array([[ 21, 121, 158],
       [ 46, 202, 273],
       [ 60, 287, 307]], dtype=int32)

In [ ]:
# MORE OPERATIONS

In [ ]:
np.sum(a) # gives sum of all elements in a 

np.int64(61)

In [ ]:
a= np.random.randint(10,50, size=(5,5))
a

array([[46, 30, 19, 48, 49],
       [38, 37, 45, 29, 12],
       [29, 33, 14, 21, 19],
       [41, 40, 17, 35, 19],
       [19, 14, 34, 45, 13]], dtype=int32)

In [ ]:
np.sum(a)

np.int64(746)

In [ ]:
np.sum(a, axis=1) # row wise

array([192, 161, 116, 152, 125])

In [ ]:
np.sum(a, axis=0) # column wise

array([173, 154, 129, 178, 112])

In [ ]:
print(np.max(a))
print(np.max(a, axis=1)) # row wise maximum
print(np.max(a, axis=0) )# column wise maximum

49
[49 45 33 41 45]
[46 40 45 48 49]


In [ ]:
print(np.min(a)) #for minimum
print(np.mean(a)) #for mean
print(np.std(a)) #for stanndard deviation
print(np.var(a)) #for variance

12
29.84
12.058789325632985
145.4144


In [ ]:
a.max(axis=1) # similar can do for min,var,std,mean,sum

array([49, 45, 33, 41, 45], dtype=int32)

## ARRAY MANIPULATION

In [ ]:
a =np.random.randint(1,10, size=(3,3))
b= np.random.randint(10,20, size =(3,3))

In [ ]:
a

array([[1, 7, 8],
       [2, 6, 9],
       [2, 6, 8]], dtype=int32)

In [ ]:
b

array([[17, 18, 11],
       [18, 19, 16],
       [12, 15, 16]], dtype=int32)

In [ ]:
a.transpose() # interchange rows and columns

array([[1, 2, 2],
       [7, 6, 6],
       [8, 9, 8]], dtype=int32)

In [ ]:
a.ravel() # convert matrix to 1d array

array([1, 7, 8, 2, 6, 9, 2, 6, 8], dtype=int32)

In [ ]:
np.sort(a) #sorting rows into ascending

array([[1, 7, 8],
       [2, 6, 9],
       [2, 6, 8]], dtype=int32)

In [ ]:
a.transpose()

array([[1, 2, 2],
       [7, 6, 6],
       [8, 9, 8]], dtype=int32)

In [ ]:
# MERGING OF ARRAYS

In [ ]:
# MERGING ALONG Y-AXIS
m_y= np.concatenate((a,b), axis= 0)
m_y

array([[ 1,  7,  8],
       [ 2,  6,  9],
       [ 2,  6,  8],
       [17, 18, 11],
       [18, 19, 16],
       [12, 15, 16]], dtype=int32)

In [ ]:
# MERGING ALONG x-AXIS
m_x= np.concatenate((a,b), axis= 1)
m_x

array([[ 1,  7,  8, 17, 18, 11],
       [ 2,  6,  9, 18, 19, 16],
       [ 2,  6,  8, 12, 15, 16]], dtype=int32)

In [ ]:
np.vstack((a,b))

array([[ 1,  7,  8],
       [ 2,  6,  9],
       [ 2,  6,  8],
       [17, 18, 11],
       [18, 19, 16],
       [12, 15, 16]], dtype=int32)

In [ ]:
np.hstack((a,b))

array([[ 1,  7,  8, 17, 18, 11],
       [ 2,  6,  9, 18, 19, 16],
       [ 2,  6,  8, 12, 15, 16]], dtype=int32)

In [ ]:
np.dstack((a,b))

array([[[ 1, 17],
        [ 7, 18],
        [ 8, 11]],

       [[ 2, 18],
        [ 6, 19],
        [ 9, 16]],

       [[ 2, 12],
        [ 6, 15],
        [ 8, 16]]], dtype=int32)

In [ ]:
# SPLITTING OF ARRAY.

In [ ]:
np.split(m_y, 2,axis=0) #gives error if array is not divided equally,array whole not divided

[array([[1, 7, 8],
        [2, 6, 9],
        [2, 6, 8]], dtype=int32),
 array([[17, 18, 11],
        [18, 19, 16],
        [12, 15, 16]], dtype=int32)]

In [ ]:
np.split(m_x, 2,axis=1)

[array([[1, 7, 8],
        [2, 6, 9],
        [2, 6, 8]], dtype=int32),
 array([[17, 18, 11],
        [18, 19, 16],
        [12, 15, 16]], dtype=int32)]

In [ ]:
# array_split
np.array_split(m_x, 2, axis=0)

[array([[ 1,  7,  8, 17, 18, 11],
        [ 2,  6,  9, 18, 19, 16]], dtype=int32),
 array([[ 2,  6,  8, 12, 15, 16]], dtype=int32)]

In [ ]:
a= np.array(["i", "love", "my india"])
a

array(['i', 'love', 'my india'], dtype='<U8')

In [ ]:
print(np.char.upper(a))
print(np.char.lower(a))
print(np.char.capitalize(a))
print(np.char.title(a))
print(np.char.swapcase(a))

['I' 'LOVE' 'MY INDIA']
['i' 'love' 'my india']
['I' 'Love' 'My india']
['I' 'Love' 'My India']
['I' 'LOVE' 'MY INDIA']


In [78]:
# append

# add values 

In [79]:
a = np.random.randint(1,10,10)

In [80]:
a

array([4, 7, 9, 5, 8, 6, 4, 1, 1, 9], dtype=int32)

In [81]:
np.append(a,300)

array([  4,   7,   9,   5,   8,   6,   4,   1,   1,   9, 300])

In [82]:
b= np.random.randint(1,10, size=(3,3))
c= np.random.randint(1,10, size=(3,3))
print(b)
print()
print(c)

[[2 6 1]
 [8 5 4]
 [8 2 9]]

[[5 6 3]
 [5 9 3]
 [3 5 4]]


In [83]:
np.append(b,c, axis=0)

array([[2, 6, 1],
       [8, 5, 4],
       [8, 2, 9],
       [5, 6, 3],
       [5, 9, 3],
       [3, 5, 4]], dtype=int32)

In [84]:
np.append(b,c, axis=1)

array([[2, 6, 1, 5, 6, 3],
       [8, 5, 4, 5, 9, 3],
       [8, 2, 9, 3, 5, 4]], dtype=int32)

In [85]:
# unique

#gives unique values of arrray

In [86]:
np.unique(a)

array([1, 4, 5, 6, 7, 8, 9], dtype=int32)

In [87]:
np.unique(b)

array([1, 2, 4, 5, 6, 8, 9], dtype=int32)

In [88]:
# where

# returns the index value if given condition is met

In [89]:
a[a>5]

array([7, 9, 8, 6, 9], dtype=int32)

In [90]:
np.where(a>5) # we get the index where this condition is satisfied

(array([1, 2, 4, 5, 9]),)

In [91]:
np.where(b>3)

(array([0, 1, 1, 1, 2, 2]), array([1, 0, 1, 2, 0, 2]))

In [92]:
np.where(b>3)[0]

array([0, 1, 1, 1, 2, 2])

In [93]:
np.where(b>3)[1]

array([1, 0, 1, 2, 0, 2])

In [94]:
a

array([4, 7, 9, 5, 8, 6, 4, 1, 1, 9], dtype=int32)

In [95]:
id(a)

2305999596944

In [96]:
a= np.append(a,100)

In [97]:
id(a)

2305999598672

In [98]:
a

array([  4,   7,   9,   5,   8,   6,   4,   1,   1,   9, 100])

In [99]:
np.where(a>3,200,a) # where ke andar jo condn ke baad jaha true ho jaha 200 se replace kro aur jaha false waha A rhne do

array([200, 200, 200, 200, 200, 200, 200,   1,   1, 200, 200])

In [100]:
np.where(b>3, 100, b)

array([[  2, 100,   1],
       [100, 100, 100],
       [100,   2, 100]], dtype=int32)

In [101]:
# argmax -- return the index of the maximum value

In [102]:
np.argmax(a)

np.int64(10)

In [103]:
np.argmax(b)

np.int64(8)

In [104]:
# argmin -- returns the index of minimum 
np.min(a)

np.int64(1)

In [105]:
np.argmin(b)

np.int64(2)

In [106]:
# cumsum -- cumlative sum
a

array([  4,   7,   9,   5,   8,   6,   4,   1,   1,   9, 100])

In [107]:
np.cumsum(a)

array([  4,  11,  20,  25,  33,  39,  43,  44,  45,  54, 154])

In [108]:
np.cumsum(b)

array([ 2,  8,  9, 17, 22, 26, 34, 36, 45])

In [109]:
np.cumsum(b, axis=0)

array([[ 2,  6,  1],
       [10, 11,  5],
       [18, 13, 14]])

In [110]:
# cumprod -- cumlative prod
np.cumprod(a)

array([        4,        28,       252,      1260,     10080,     60480,
          241920,    241920,    241920,   2177280, 217728000])

In [111]:
np.cumprod(b, axis=1)

array([[  2,  12,  12],
       [  8,  40, 160],
       [  8,  16, 144]])

In [124]:
#isin -- wo element exist krta h ya nhi usmein
a

array([  4,   7,   9,   5,   8,   6,   4,   1,   1,   9, 100])

In [116]:
b= np.random.randint(1,30, size=(5,5))
b

array([[11,  5, 22, 26,  8],
       [18, 23, 14,  5,  2],
       [23, 26, 14, 17, 11],
       [15, 16,  6, 18,  3],
       [29, 11, 24, 11,  8]], dtype=int32)

In [117]:
x = [1,2,5.9]

In [118]:
np.isin(a, x)

array([False, False, False, False, False, False, False,  True,  True,
       False, False])

In [119]:
a[np.isin(a, x)]

array([1, 1])

In [121]:
np.isin(b,x)

array([[False, False, False, False, False],
       [False, False, False, False,  True],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [123]:
b[np.isin(b,x)]

array([2], dtype=int32)

In [137]:
# np.put -- put the value at the given index

a

array([100,   7,   9, 100,   8,   6,   4, 100,   1,   9, 100])

In [129]:
np.put(a,0,100)
a

array([100,   7,   9,   5,   8,   6,   4,   1,   1,   9, 100])

In [131]:
np.put(a,[3,7],100)
a

array([100,   7,   9, 100,   8,   6,   4, 100,   1,   9, 100])

In [136]:
np.put(b, 4, 100)
b

array([[ 11,   5,  22,  26, 100],
       [ 18,  23, 100,   5,   2],
       [ 23,  26,  14,  17,  11],
       [ 15,  16,   6,  18,   3],
       [ 29,  11,  24,  11,   8]], dtype=int32)

In [140]:
# np.delete -- remove the value from the given index

a

array([100,   7,   9, 100,   8,   6,   4, 100,   1,   9, 100])

In [141]:
np.delete(a, 1)

array([100,   9, 100,   8,   6,   4, 100,   1,   9, 100])

In [142]:
np.delete(b,4)

array([ 11,   5,  22,  26,  18,  23, 100,   5,   2,  23,  26,  14,  17,
        11,  15,  16,   6,  18,   3,  29,  11,  24,  11,   8], dtype=int32)

In [146]:
np.delete(b, 4, axis=1) #delete krdega uss axis m

array([[ 11,   5,  22,  26],
       [ 18,  23, 100,   5],
       [ 23,  26,  14,  17],
       [ 15,  16,   6,  18],
       [ 29,  11,  24,  11]], dtype=int32)

In [148]:
# np.any -- ye indexwise nhi dega pura array ke liye deta ek boolean

np.any(b>500)

np.False_

In [149]:
np.any(b>500, axis=1)

array([False, False, False, False, False])

ANY FUNCTION CAN ONLY MAKE CHANGES TO THE ARRAY ONLY WHEN IT IS NOT CHANGING THE LENGTH OF ARRAY OTHERWISE IF IT CHANGES THEN WE HAVE TO ASSIGN THE FUNCTION TO THE VARIABLE BY OWN

In [151]:
# np.applyalong.axis
np.apply_along_axis(lambda x: min(x), arr=b, axis = 1)

array([ 5,  2, 11,  3,  8], dtype=int32)

In [152]:
# np.fill diagonals.

b

array([[ 11,   5,  22,  26, 100],
       [ 18,  23, 100,   5,   2],
       [ 23,  26,  14,  17,  11],
       [ 15,  16,   6,  18,   3],
       [ 29,  11,  24,  11,   8]], dtype=int32)

In [154]:
np.fill_diagonal(b, 5000)
b

array([[5000,    5,   22,   26,  100],
       [  18, 5000,  100,    5,    2],
       [  23,   26, 5000,   17,   11],
       [  15,   16,    6, 5000,    3],
       [  29,   11,   24,   11, 5000]], dtype=int32)

In [155]:
# comparing of two axis

In [156]:
a= np.random.randint(1,20, size=(4,4))
b= np.random.randint(10,30, size=(4,4))

In [157]:
a

array([[ 1,  1, 13, 19],
       [13, 18, 13,  6],
       [15,  9, 12, 14],
       [ 7,  6,  6, 11]], dtype=int32)

In [158]:
b

array([[11, 26, 14, 29],
       [15, 20, 13, 13],
       [26, 25, 11, 23],
       [23, 29, 18, 13]], dtype=int32)

# ASSIGNMENT

#### Given a 2D array, find the row that has the maximum sum of all its elements

In [160]:
a= np.random.randint(1,100, size=(5,5))
a

array([[80, 13, 12, 31, 66],
       [91, 83, 94, 53, 34],
       [71,  1, 81, 58, 12],
       [73, 69, 79, 61, 14],
       [85, 97, 90, 69,  5]], dtype=int32)

In [166]:
row= np.argmax(np.sum(a, axis=1))+1
print("The row that has max sum of elements is",row)

The row that has max sum of elements is 2


#### Given an array, count the occurence of each unique element

In [168]:
a= np.random.randint(1,10, size=(5,5))
a

array([[9, 7, 1, 3, 4],
       [4, 9, 5, 9, 2],
       [5, 9, 4, 9, 3],
       [7, 6, 4, 6, 3],
       [3, 2, 9, 3, 5]], dtype=int32)

In [171]:
Values= np.unique(a, return_counts= True)[0]
Counts= np.unique(a, return_counts= True)[1]


In [173]:
for i in range(len(Values)):
    print(Values[i],Counts[i],end="")
    print()

1 1
2 2
3 5
4 4
5 3
6 2
7 2
9 6


#### You have a 2D NumPy array where each row represents a customer's purchase history. The first column is the customer ID, and the second column is the total amount spent on purchases. You need to: purchase_data = np.array([[1, 1200], [2, 850], [3, 1500], [4, 600], [5, 2000], [6, 950]]) Identify customers who have spent more than $1000 in total. Group customers into two categories: "High Spend" (greater than $1000) and "Low Spend" (less than or equal to $1000)


In [174]:
purchase_data = np.array([[1, 1200], [2, 850], [3, 1500], [4, 600], [5, 2000], [6, 950]]) 
purchase_data

array([[   1, 1200],
       [   2,  850],
       [   3, 1500],
       [   4,  600],
       [   5, 2000],
       [   6,  950]])

In [190]:
# spend more than 1000
print(f"Customer id of more than 1000 : {purchase_data[purchase_data[:,1]>1000][:,0]}")

# grouping
b= np.where(purchase_data[:,1]>1000, "High Spend" , "Low Spend")

Customer id of more than 1000 : [1 3 5]


In [192]:
np.concatenate((purchase_data[:,0].reshape(6,1),b.reshape(6,1)), axis=1)

array([['1', 'High Spend'],
       ['2', 'Low Spend'],
       ['3', 'High Spend'],
       ['4', 'Low Spend'],
       ['5', 'High Spend'],
       ['6', 'Low Spend']], dtype='<U21')

In [191]:
purchase_data[:,0].reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [184]:
np.where(purchase_data[:,1]>1000) # wrong interprentation- gives array index not cid

(array([0, 2, 4]),)